import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-stone-500">
          <div className="container flex items-center justify-between py-3 mx-auto">
            <div>
              <h1 className="text-3xl text-green-500">My App</h1>
            </div>
            <div className="flex gap-4">
              <Link className="btn" href="/foods">
                Foods
              </Link>
              <Link className="btn" href="/reviews">
                Reviews
              </Link>
            </div>
          </div>
        </header>

        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
